### PR TITLE
My OCD is forcing me to correct a typo

### PR DESCRIPTION
**Pull request by swiftcodex**
Super awesome job // Congrats on open-sourcing! Can't wait to really dive-in and check it out. (Feel free to ignore my trivial readme correction). 😎

### CODE REVIEW

**Comment by colinta** [comment]
Can you fix the specs while your at it?? :wink:

**Comment by colinta** [comment]
Oh, I guess I can't merge from a phone, weird. 

I noticed you used our branch naming structure - a nice touch!

**Comment by swiftcodex** [comment]
It's cool to see a well-architected project using Moya. Really nice stuff.

**Comment by colinta** [comment]
Oh yeah we're big fans of Moya - and "enum-oriented-design" in general!  Prob my 2nd favorite Swift language feature, after Optional.

**Comment by steam** [comment]
Thanks for PR @swiftcodex 👌

**Pull request merged**
