### PR TITLE
Discover and Categories should share grid/list setting

### PR DESCRIPTION
**Pull request by colinta**
[Fixes #126818887] https://www.pivotaltracker.com/story/show/126818887

### CODE REVIEW

**Comment by steam** [comment]
Hmm, tiny? I'm guessing this has all the buy button stuff in it. What should I review?

**Comment by colinta** [comment]
That's really weird, locally the only commit is 606b936, and no amount of pushing and rebasing seems to matter to github.

**Comment by colinta** [comment]
There we go - I pushed an empty commit (`git commit --allow-empty -m "tap tap tap"`), pushed, then removed that commit (`git reset --hard HEAD^`) and force pushed. That seemed to "wake up" github's diff.

**Comment by steam** [comment]
Nice work.

**Comment by colinta** [comment]
```
Specs.AsyncOperationSpec
  AsyncOperation__block_added_later__does_not_run_when_cancelled, Waited more than 1.0 second
  /Users/travis/build/ello/ello-ios/Specs/Networking/AsyncOperationSpec.swift:81

                    queue.addOperation(subject)
                    waitUntil { done in
                        delay(0.1) {
```
Not concerned about this failure, though I might try to figure it out when I have a free sec (I see it locally *now and then*.

**Comment by steam** [comment]
👍

**Pull request merged**
