### PR TITLE
Fixes to category button frame, and refactor repostedByButton frame

### PR DESCRIPTION
**Pull request by colinta**
No more unnecessary truncation on `categoryButton`, and the `repostedByButton` frame calculation was more confusing than necessary.

### CODE REVIEW

**Comment by steam** [comment]
Should we have snapshot specs here to verify this?

**Comment by colinta** [comment]
Good call, I'll update the existing ones to use a long category name.

**Comment by steam** [comment]
:metal:

**Comment by colinta** [comment]
Oops, just noticed another edge case (in grid, the category can/should be `26pt` wider). Another PR, built on top of this one.

**Pull request merged**
