### PR TITLE
Version 1.14

### PR DESCRIPTION
**Pull request by colinta**
This PR will grow as the 1.14 PRs get merged into `next/1.14.0`.  It's just a "catch all" branch/PR.

### CODE REVIEW

**Comment by steam** [comment]
👍

**Comment by colinta** [comment]
Cool - the failure in specs is because I rebased these commits from `cg/new/onboarding` onto `next/1.14.0`, and there was a slight difference in where the `Crashlytics` framework was imported.  Gonna merge so I can use this in ongoing `cg/new/onboarding` work.

**Comment by colinta** [comment]
Ahh shit.  Wrong damn branch.

**Comment by colinta** [comment]
This should have been a WIP branch anyway.

**Pull request merged**
