### PR TITLE
Fix or ignore remaining Xcode 8 spec failures

### PR DESCRIPTION
**Pull request by steam**
Xcode 8 has introduced instability in our test suite. Specifically, async tests fail or pass inconsistently. Unfortunately we have to mark several tests as pending to get a consistent green run.

The hope is that the upcoming move to Swift 3 will fix some / all of these.

We're also using NSUserDefaults.standardUserDefaults() in tests now due to incorrect behavior when using the group defaults in the test suite.

### CODE REVIEW

**Comment by colinta** [comment]
Might need a `.travis.yml` change, too, to use `osx_image: xcode8`

**Comment by steam** [comment]
Yeah, it will need the travis change. I was still getting errors over in the ElloUIFonts project with `xcode8`. Something to do with xctool, I've not investigated further.

**Comment by steam** [comment]
👍

**Comment by steam** [comment]
Once the specs go green "fingers crossed", lets merge it.

**Comment by steam** [comment]
@colinta, the specs failed again due to an error. Are you in the middle of anything related to this PR? Should I dive in and get this over the line?

**Comment by colinta** [comment]
Shoot, just saw your comment, I restarted them because I couldn't figure out WHAT error caused them to fail.  All yours, though, I didn't mean to get in the way! :smiley:

**Pull request merged**
