### PR TITLE
Make 'pod repo update' silent

### PR DESCRIPTION
**Pull request by colinta**
So our Travis log is manageable.

### CODE REVIEW

**Comment by steam** [comment]
Very nice 👍

**Comment by colinta** [comment]
pod repo update

Much nicer!

**Comment by colinta** [comment]
screen shot 2016-06-23 at 10 52 15 am

BOOO

**Comment by steam** [comment]
Man, what the heck.

**Comment by colinta** [comment]
Tried again, this time it worked ¯\(º_o)/¯

**Pull request merged**
