### PR TITLE
Adds NFP to the drawer

### PR DESCRIPTION
**Pull request by caseydoran**

### CODE REVIEW

**Comment by caseydoran** [comment]
done @steam - Thanks!

**Comment by caseydoran** [comment]
@steam how do I restart the buddybuild ?

**Comment by steam** [comment]
@caseydoran - buddybuild isn't up and running yet, don't sweat it.

**Comment by caseydoran** [comment]
@steam looks like travis is also struggling looking for "StagingOauthKey"

**Comment by steam** [comment]
@caseydoran - Travis is also a mess right now. It hasn't succeeded since we switched to Swift 3. Don't worry about it.

**Pull request merged**
