### PR TITLE
Fixes insertion point in Profile when creating a post

### PR DESCRIPTION
**Pull request by colinta**
We added 3 cells, so change `1` to `4`.

Magic numbers == 😢

### CODE REVIEW

**Comment by jayzes** [comment]
✨

**Comment by steam** [comment]
Lets hold off on this. We have the generators coming and this issue should be handled by the generators.

**Comment by colinta** [comment]
OTOH, we could include this in 1.9.1, and then override it with the stream generators in 1.10.

**Comment by steam** [comment]
I think we should since we're not including generators in the next build.

**Pull request merged**
