### PR TITLE
Changes avatar size from 60 to 40 in list view

### PR DESCRIPTION
**Pull request by colinta**

### CODE REVIEW

**Comment by steam** [comment]
👍

**Comment by colinta** [comment]
Rebasing to get the fixes from #70

**Comment by colinta** [comment]
I tried a lower tolerance, because otherwise the snapshot specs were passing *without* updating them to the new size.  Seems like either the tolerance has to be set high (false negatives) or specs fail (false positives) when the specs are run on Travis. WTH. 😟

**Comment by steam** [comment]
Thats a bummer.

**Comment by colinta** [comment]
Locally all specs pass w/ tolerance set to `0` - I'm curious what specs will fail on Travis w/ this setting.

Wondering if we should take the time to get [`second_curtain`](https://github.com/AshFurrow/second_curtain) setup, that's Ash Furrow's solve for this problem.

**Comment by steam** [comment]
`second_curtain` seems cool, I say go for it.

**Comment by colinta** [comment]
@jayzes Any chance you could help me out with the S3 configuration portion?

**Comment by colinta** [comment]
(@jayzes https://github.com/AshFurrow/second_curtain#usage)

**Comment by colinta** [comment]
```Executed 2018 tests, with 0 failures (0 unexpected) in 117.948 (119.042) seconds```

**Pull request merged**
