### PR TITLE
Updates Moya to 6.5, and Result to 2.0

### PR DESCRIPTION
**Pull request by colinta**
Reduces Swift 2.2 warnings, and keeps us fresh and clean.

### CODE REVIEW

**Comment by colinta** [comment]
This error is so weird.  Why can't Travis see Moya v6.5? (installs locally, no problem)

**Comment by colinta** [comment]
@steam specs are green, this is ready for review

**Comment by steam** [comment]
MERGE IT NOW!

**Comment by colinta** [comment]
haha

**Pull request merged**
