### PR TITLE
Add Caffeine for APIs on ello.co and ello.ninja

### PR DESCRIPTION
**Pull request by wittedhaddock**
This PR will show request times in console.

We still owe you the "A/B testing boilerplate," too.

### CODE REVIEW

**Comment by colinta** [comment]
Nice!  Thanks James, excited to try this out!

I noticed that `Podfile.lock` changed – makes total sense given that we only hand out the open source versions of the Certs and Fonts repos.  But, @steam I wonder how we could avoid merging changes to this file – or if we should just merge the changes and then revert them ourselves later?  I can't think of any clever way to handle the private vs open-source Pod differences.

**Comment by steam** [comment]
Thats a good question @colinta. I'm fine merging them and reverting them later. No one is going to inadvertently build from a commit that has the open source fonts when submitting the App Store.

**Comment by colinta** [comment]
Yeah I was imagining a workflow where we merge into a temporary branch, then checkout the current `Podfile.lock` from master, then merge that branch into master.  So the PR gets merged, and `Podfile.lock` would not need to be updated.
```
git checkout -b wittedhaddock-jg/feature/caffeine swift3.0
git pull https://github.com/wittedhaddock/ello-ios.git jg/feature/caffeine
# revert podfile.lock
git checkout Podfile.lock swift3.0  # or master, later on
git commit -m "reverting Podfile.lock"
# merge the "fixed" branch in - people using swift3.0 branch would never have an
# out-of-sync Podfile
git checkout swift3.0  # or master
git merge wittedhaddock-jg/feature/caffeine
```

**Comment by wittedhaddock** [comment]
@colinta Np! (Let me know if you'd like me to change anything on my end to accommodate the `Podfile.lock` considerations.)

Also, @drewcrawford just signed off on the new API filtering by `URLRequest`'s `httpMethod`, which I'll push shortly and you should see downstream. We can divert those async`HEAD`s from using Caffeine :)

**Comment by steam** [comment]
@wittedhaddock, just a heads up that we are close to shipping our last non-swift 3 release. We've gone through a couple rounds of bug fixes and hope to submit to Apple soon. Once that is submitted we'll be focussing all our attention on the swift 3 code and will be able to move forward with the caffeine test.

**Comment by wittedhaddock** [comment]
Thanks for the update @steam! All sounds good.

**Comment by steam** [comment]
@wittedhaddock You mentioned in your email (I forwarded it to @colinta) that we should not evaluate this PR until you investigate a bit further. All that sounds good. Let us know when you'd like us to put out a build with this PR included in it. We're planning on a TestFlight build of #253 today or tomorrow so we're getting close.

**Comment by steam** [comment]
Closing for now since Caffeine is on hold. Thanks @wittedhaddock and @drewcrawford!

**Pull request closed without merging**
