### PR TITLE
Changes behavior of red-dot reloading in Notifications and Streams

### PR DESCRIPTION
**Pull request by colinta**
Tapping red dot in Notifications shows the loader (regression fix), and in Streams tapping the red dot while viewing "Starred" will switch to "Following" and reload the page.

### CODE REVIEW

**Comment by colinta** [comment]
Running specs now, btw.  This PR includes `sd/fix/specs`, so we should probably merge that one first.

**Comment by colinta** [comment]
```Executed 2602 tests, with 0 failures (0 unexpected) in 275.870 (276.938) seconds```

**Comment by jayzes** [comment]
@colinta will that reload trigger a reload from the server?

**Comment by colinta** [comment]
@jayzes I hope so!  But yeah, that's the point.  I'm actually not sure I understand your question.

**Comment by colinta** [comment]
Like I'm answering a tautology.  Will telling me your first name give me the information I need to call you by your first name?  *No it will not!*

**Comment by jayzes** [comment]
Haha, fair enough. I was just confirming that it was reloading from the server and not from locally-cached data. Was virtually positive that it was, but wanted to make sure I wasn't missing something.

**Comment by colinta** [comment]
Ahh gotcha - yes, it's a "go fetch the latest data" kinda reload, not the "hey collection view, are you awake?  Can you reload your cells?  No? *Crash!?*  Why did you crash?" kinda reload that is the bread and butter of iOS development. :trollface:

**Comment by jayzes** [comment]
🤘

**Pull request merged**
