### PR TITLE
Updating the name of "APNS Pusher" to "Knuff" in Readme.

### PR DESCRIPTION
**Pull request by blommegard**
Thanks for the mention! :)

### CODE REVIEW

**Comment by steam** [comment]
Thanks for the PR @blommegard :metal: CI failed for some reason. I restarted it. I'll merge this in as soon as we're green (there is no reason your PR would break CI).

**Comment by colinta** [comment]
Thank you for catching that!  We're big fans of Knuff - thanks! 🍻

**Comment by colinta** [comment]
Obv this PR doesn't affect the specs, so I propose we merge, and w/ the travis fix in there, the next PR should be green.

**Comment by colinta** [comment]
Or, @blommegard, if you merge / rebase onto master, you should get the fixes to `.travis.yml` that I pushed up.

**Comment by blommegard** [comment]
All done!

**Comment by steam** [comment]
Gonna go ahead and merge this, we'll save taming travis for another day.

**Pull request merged**
