### PR TITLE
adds the robrix/Box license

### PR DESCRIPTION
**Pull request by colinta**

### CODE REVIEW

**Comment by steam** [comment]
Giving this a thumbs up for now. We should try using the pod `pod 'Box', '~> 2.0'` moving forward. Do you remember why we didn't initially? My (terrible) memory is that we had a naming conflict at the time.

**Comment by colinta** [comment]
Box doesn't have a podspec

**Comment by steam** [comment]
How does it show up in the search results with a copyable pod file line?

**Comment by colinta** [comment]
https://github.com/robrix/Box

¯\_(ツ)_/¯

**Comment by colinta** [comment]
I guess someone else is maintaining the pod - I really don't know.

**Comment by steam** [comment]
I've seen repos like this before that have no pod spec but have pods none-the-less. Black Magic 🌈 .

**Comment by colinta** [comment]
> Maintained by Gordon Fontenot, Ash Furrow

https://cocoapods.org/pods/Box

**Comment by steam** [comment]
Sure enough. "Sean, RTFM" is what you meant to say. 😏

**Pull request merged**
